# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.11.0'

target 'RecordBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecordBook

  target 'RecordBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecordBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RecordBook-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecordBook-tvOS

  target 'RecordBook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
